id: A7B7F9611
title: 'The Lotus of Faith: A Supplication to the Successive Lives of Shechen Rabjam'
type: translation
pechas:
- I8DB4848D
- I733812B0
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:38:34.275118
  last_modified_at: 2023-01-04 11:38:34.275130
  collections:
  - Dilgo Khyentse Rinpoche Series
  - Works of Tibetan Masters
alignment_to_base:
  I8DB4848D/6F49: B44A
  I733812B0/A447: B44A
